[package]
name = "lact-cli"
version = "0.8.5"
edition = "2024"

[dependencies]
lact-client = { path = "../lact-client" }
lact-schema = { path = "../lact-schema", features = ["args"] }
anyhow = "1.0.79"
tokio = { workspace = true, features = ["rt"] }
