[package]
name = "lact-client"
version = "0.4.6"
edition = "2021"

[dependencies]
lact-schema = { path = "../lact-schema" }
anyhow = "1.0.75"
nix = { version = "0.27.1", default-features = false }
serde = "1.0.189"
tracing = "0.1.39"
serde_json = "1.0.107"
